# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
# cache: cocoapods
# podfile: Example/Podfile
before_install:
# - gem install cocoapods -v '0.39.0' # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
    - xcodebuild -version
    - xcodebuild -showsdks
    - set -o pipefail && xcodebuild clean
    - set -o pipefail && xcodebuild test -workspace ForecastIO.xcworkspace -scheme "ForecastIO iOS" -destination "platform=iOS Simulator,OS=8.1,name=iPhone 6" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
    - set -o pipefail && xcodebuild clean
    - set -o pipefail && xcodebuild test -workspace ForecastIO.xcworkspace -scheme "ForecastIO OS X" -destination "arch=x86_64" -sdk macosx10.11 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
